### ISSUE TITLE
Don't support node v10.

### ISSUE THREAD

**Issue by Dimitrioglo** [ddimitrioglo/web-boost#17]
1. I run command: `node node_modules/web-boost/bin/run.js 8000`
2. My environment: `Linux 64-bit with Node.js 10.x`
3. Error: `node node_modules/web-boost/bin/run.js 8000
(node:3704) ExperimentalWarning: The fs.promises API is experimental
events.js:167
      throw er; // Unhandled 'error' event 
`

**Comment by ddimitrioglo** [comment]
Closing. Can not reproduce the issue.

```
[www]: node -v
v10.15.0
[www]: node node_modules/web-boost/bin/run.js 8000
💡 [2019-01-10T20:22:46.713Z] Ok
```
