### ISSUE TITLE
On Ubuntu 18 npm install fails.

### ISSUE THREAD

**Issue by gcaraman-zz** [ddimitrioglo/web-boost#18]
This error is returned: pngquant failed to build, make sure that libpng-dev is installed.

The issue is fixed after libpng-dev is installed (sudo apt-get install libpng-dev).

**Comment by ddimitrioglo** [comment]
@gcaraman thank you for reporting this, will add as prerequisites

**Comment by ddimitrioglo** [comment]
will be released in `v1.4.0`
