### ISSUE TITLE
Add ability to add global variable in web-boost.json

### ISSUE THREAD

**Issue by mracila25** [ddimitrioglo/web-boost#22]

**Comment by ddimitrioglo** [comment]
Hi @mracila25,

This is cool idea and it definitely will be implemented 😉 
Thank for reaching out.

**Comment by ddimitrioglo** [comment]
In order to provide the best user experience, a decision was taken that since `v1.4.0` web-boost will support 2 config formats:
* `web-boost.json` for simple use cases w/o any logic
* `web-boost.js` for complex use cases or those who likes everything to be dynamic 

> the only thing you have to do `module.exports = { // whole config }`

**Comment by ddimitrioglo** [comment]
@mracila25 Implemented in `web-boost@1.4.0`
